### ISSUE TITLE
[BUG] can't save preset on windows

### ISSUE THREAD

**Issue by AnityEx** [schroef/Rigify-Save-Presets#1]
**OS:**
 - OS: Windows

**ADDON:**
 - Version: 0.0.9

**Describe the bug**
cant save preset

**To Reproduce**
1. select meta rig
2. name preset and choose folder
3. add rig preset
4. error

**error**
Python: Traceback (most recent call last):
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Rigify-Save-Presets\__init__.py", line 305, in execute
    f = open(os.path.join(fpath), 'w')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender 2.92\\2.92\\scripts\\addons\\rigify\\metarigs/Animals\\elephant_anityex.py'

location: <unknown location>:-1

**Comment by schroef** [comment]
Thanks for letting me know that, it should normally work in that area. I just tried my version and seems to work fine.
Do other preset save, for instance can you any other preset?

You are using this "Rig save function' right? Its the right one in the save options
![save-metarig-preset](https://user-images.githubusercontent.com/6923008/116828741-92a57000-ab6e-11eb-85bc-fc145afaedd4.png)



PS did you change filenames? I see the 2nd line in that error is missing a slash.
```File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Rigify-Save-Presets_init_.py"```
It should show like this
```File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Rigify-Save-Presets\_init_.py"```

What i see in your path is that it uses mixed slashed, i see forward and backwards.
So you selected the animals folder and the name of the file was "elephant_anityex.py". That should work, not sure where that other backward slash came from.


It looks inside the metarig folder and show existing folders, you can add a new subfolder if you like. But you did not do that i see.

Could i perhaps have that metarig in blend file to check it? I only need the metarig, clear everything else.

**Comment by AnityEx** [comment]
yeah I used that option now and...

`Python: Traceback (most recent call last):
  File "C:\Users\Alan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\Rigify-Save-Presets-master\__init__.py", line 305, in execute
    f = open(os.path.join(fpath), 'w')
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender 2.93\\2.93\\scripts\\addons\\rigify\\metarigs/Animals\\anityexs_elephant_rig.py'

location: <unknown location>:-1

`
i even got the rig on another file and has this soo maybe its a windows thing

[Elephant Metarig.zip](https://github.com/schroef/Rigify-Save-Presets/files/6712156/Elephant.Metarig.zip)

**Comment by AnityEx** [comment]
oh god
i opened blender as administrator and saved my metarig as it is meant to

**Comment by schroef** [comment]
Quite weird its a admin thing. Ive never experienced this with saving presets. Im basically using the default method Blender uses for saving presets.

Ill try your attached file.
