### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by uayten** [schroef/Rigify-Save-Presets#2]
**OS:**
 - OS: Windows

**ADDON:**
 - Version: 0.0.9

**Describe the bug**
I can't initialize the addon

**To Reproduce**
1. Install Addon on Blender 4.0.2
2. Click on checkbox to load the addon
2. See error

**Screenshots**
![image](https://github.com/schroef/Rigify-Save-Presets/assets/43273078/da3b9e33-a204-4897-924e-2147c88b56a9)

**Comment by schroef** [comment]
It needs update for bl 4. I'll try to see if I can fix this fast

**Comment by schroef** [comment]
I added a response here how to work around it for now. The function basically alreay exists in Rigify itself, but it tedious to work with

https://github.com/schroef/Rigify-Save-Presets/issues/3

In this video by CGDive you can see how it works, doing it the manual way
https://www.youtube.com/watch?v=o6_AzySr64c

**Comment by schroef** [comment]
It's updated know to work on bl4.0+ see https://github.com/schroef/Rigify-Save-Presets/releases/tag/v0.1.1
